# Generated by Django 5.1.1 on 2025-01-09 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_airport_alter_flight_destination_alter_flight_orign'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='orign',
            new_name='origin',
        ),
    ]
